// this file was auto-generated by wrapit v1.6.0
#include "Wrapper.h"

#include "jlXRootD.h"
#include "dbg_msg.h"
#include "jlcxx/functions.hpp"
#include "jlcxx/stl.hpp"

namespace jlcxx {
  template<> struct IsMirroredType<XrdCl::FileSystem> : std::false_type { };
  template<> struct DefaultConstructible<XrdCl::FileSystem> : std::false_type { };
}

// Class generating the wrapper for type XrdCl::FileSystem
// signature to use in the veto file: XrdCl::FileSystem
struct JlXrdCl_FileSystem: public Wrapper {

  JlXrdCl_FileSystem(jlcxx::Module& jlModule): Wrapper(jlModule){
    DEBUG_MSG("Adding wrapper for type XrdCl::FileSystem (" __HERE__ ")");
    // defined in /Users/mato/.julia/artifacts/d7f8626a7055397045bff10d1f18132236662705/include/xrootd/XrdCl/XrdClFileSystem.hh:202:9
    jlcxx::TypeWrapper<XrdCl::FileSystem>  t = jlModule.add_type<XrdCl::FileSystem>("XrdCl!FileSystem");
    type_ = std::unique_ptr<jlcxx::TypeWrapper<XrdCl::FileSystem>>(new jlcxx::TypeWrapper<XrdCl::FileSystem>(jlModule, t));
  }

  void add_methods() const{
    auto& t = *type_;


    DEBUG_MSG("Adding wrapper for void XrdCl::FileSystem::FileSystem(const XrdCl::URL &, bool) (" __HERE__ ")");
    // defined in /Users/mato/.julia/artifacts/d7f8626a7055397045bff10d1f18132236662705/include/xrootd/XrdCl/XrdClFileSystem.hh:216:7
    t.constructor<const XrdCl::URL &>(/*finalize=*/jlcxx::finalize_policy::yes, jlcxx::arg("this"), jlcxx::arg("url")    );
    t.constructor<const XrdCl::URL &, bool>(/*finalize=*/jlcxx::finalize_policy::yes, jlcxx::arg("this"), jlcxx::arg("url"), jlcxx::arg("enablePlugIns")    );

    DEBUG_MSG("Adding wrapper for XrdCl::XRootDStatus XrdCl::FileSystem::Locate(const std::string &, XrdCl::OpenFlags::Flags, XrdCl::ResponseHandler *, uint16_t) (" __HERE__ ")");
    // signature to use in the veto list: XrdCl::XRootDStatus XrdCl::FileSystem::Locate(const std::string &, XrdCl::OpenFlags::Flags, XrdCl::ResponseHandler *, uint16_t)
    // defined in /Users/mato/.julia/artifacts/d7f8626a7055397045bff10d1f18132236662705/include/xrootd/XrdCl/XrdClFileSystem.hh:235:20
    t.method("Locate", [](XrdCl::FileSystem& a, const std::string & arg0, XrdCl::OpenFlags::Flags arg1, XrdCl::ResponseHandler * arg2)->XrdCl::XRootDStatus { return a.Locate(arg0, arg1, arg2); }, jlcxx::arg("this"), jlcxx::arg("path"), jlcxx::arg("flags"), jlcxx::arg("handler"));
    t.method("Locate", [](XrdCl::FileSystem& a, const std::string & arg0, XrdCl::OpenFlags::Flags arg1, XrdCl::ResponseHandler * arg2, uint16_t arg3)->XrdCl::XRootDStatus { return a.Locate(arg0, arg1, arg2, arg3); }, jlcxx::arg("this"), jlcxx::arg("path"), jlcxx::arg("flags"), jlcxx::arg("handler"), jlcxx::arg("timeout"));
    t.method("Locate", [](XrdCl::FileSystem* a, const std::string & arg0, XrdCl::OpenFlags::Flags arg1, XrdCl::ResponseHandler * arg2)->XrdCl::XRootDStatus { return a->Locate(arg0, arg1, arg2); }, jlcxx::arg("this"), jlcxx::arg("path"), jlcxx::arg("flags"), jlcxx::arg("handler"));
    t.method("Locate", [](XrdCl::FileSystem* a, const std::string & arg0, XrdCl::OpenFlags::Flags arg1, XrdCl::ResponseHandler * arg2, uint16_t arg3)->XrdCl::XRootDStatus { return a->Locate(arg0, arg1, arg2, arg3); }, jlcxx::arg("this"), jlcxx::arg("path"), jlcxx::arg("flags"), jlcxx::arg("handler"), jlcxx::arg("timeout"));

    DEBUG_MSG("Adding wrapper for XrdCl::XRootDStatus XrdCl::FileSystem::Locate(const std::string &, XrdCl::OpenFlags::Flags, XrdCl::LocationInfo *&, uint16_t) (" __HERE__ ")");
    // signature to use in the veto list: XrdCl::XRootDStatus XrdCl::FileSystem::Locate(const std::string &, XrdCl::OpenFlags::Flags, XrdCl::LocationInfo *&, uint16_t)
    // defined in /Users/mato/.julia/artifacts/d7f8626a7055397045bff10d1f18132236662705/include/xrootd/XrdCl/XrdClFileSystem.hh:251:20
    t.method("Locate", [](XrdCl::FileSystem& a, const std::string & arg0, XrdCl::OpenFlags::Flags arg1, XrdCl::LocationInfo *& arg2)->XrdCl::XRootDStatus { return a.Locate(arg0, arg1, arg2); }, jlcxx::arg("this"), jlcxx::arg("path"), jlcxx::arg("flags"), jlcxx::arg("response"));
    t.method("Locate", [](XrdCl::FileSystem& a, const std::string & arg0, XrdCl::OpenFlags::Flags arg1, XrdCl::LocationInfo *& arg2, uint16_t arg3)->XrdCl::XRootDStatus { return a.Locate(arg0, arg1, arg2, arg3); }, jlcxx::arg("this"), jlcxx::arg("path"), jlcxx::arg("flags"), jlcxx::arg("response"), jlcxx::arg("timeout"));
    t.method("Locate", [](XrdCl::FileSystem* a, const std::string & arg0, XrdCl::OpenFlags::Flags arg1, XrdCl::LocationInfo *& arg2)->XrdCl::XRootDStatus { return a->Locate(arg0, arg1, arg2); }, jlcxx::arg("this"), jlcxx::arg("path"), jlcxx::arg("flags"), jlcxx::arg("response"));
    t.method("Locate", [](XrdCl::FileSystem* a, const std::string & arg0, XrdCl::OpenFlags::Flags arg1, XrdCl::LocationInfo *& arg2, uint16_t arg3)->XrdCl::XRootDStatus { return a->Locate(arg0, arg1, arg2, arg3); }, jlcxx::arg("this"), jlcxx::arg("path"), jlcxx::arg("flags"), jlcxx::arg("response"), jlcxx::arg("timeout"));

    DEBUG_MSG("Adding wrapper for XrdCl::XRootDStatus XrdCl::FileSystem::DeepLocate(const std::string &, XrdCl::OpenFlags::Flags, XrdCl::ResponseHandler *, uint16_t) (" __HERE__ ")");
    // signature to use in the veto list: XrdCl::XRootDStatus XrdCl::FileSystem::DeepLocate(const std::string &, XrdCl::OpenFlags::Flags, XrdCl::ResponseHandler *, uint16_t)
    // defined in /Users/mato/.julia/artifacts/d7f8626a7055397045bff10d1f18132236662705/include/xrootd/XrdCl/XrdClFileSystem.hh:269:20
    t.method("DeepLocate", [](XrdCl::FileSystem& a, const std::string & arg0, XrdCl::OpenFlags::Flags arg1, XrdCl::ResponseHandler * arg2)->XrdCl::XRootDStatus { return a.DeepLocate(arg0, arg1, arg2); }, jlcxx::arg("this"), jlcxx::arg("path"), jlcxx::arg("flags"), jlcxx::arg("handler"));
    t.method("DeepLocate", [](XrdCl::FileSystem& a, const std::string & arg0, XrdCl::OpenFlags::Flags arg1, XrdCl::ResponseHandler * arg2, uint16_t arg3)->XrdCl::XRootDStatus { return a.DeepLocate(arg0, arg1, arg2, arg3); }, jlcxx::arg("this"), jlcxx::arg("path"), jlcxx::arg("flags"), jlcxx::arg("handler"), jlcxx::arg("timeout"));
    t.method("DeepLocate", [](XrdCl::FileSystem* a, const std::string & arg0, XrdCl::OpenFlags::Flags arg1, XrdCl::ResponseHandler * arg2)->XrdCl::XRootDStatus { return a->DeepLocate(arg0, arg1, arg2); }, jlcxx::arg("this"), jlcxx::arg("path"), jlcxx::arg("flags"), jlcxx::arg("handler"));
    t.method("DeepLocate", [](XrdCl::FileSystem* a, const std::string & arg0, XrdCl::OpenFlags::Flags arg1, XrdCl::ResponseHandler * arg2, uint16_t arg3)->XrdCl::XRootDStatus { return a->DeepLocate(arg0, arg1, arg2, arg3); }, jlcxx::arg("this"), jlcxx::arg("path"), jlcxx::arg("flags"), jlcxx::arg("handler"), jlcxx::arg("timeout"));

    DEBUG_MSG("Adding wrapper for XrdCl::XRootDStatus XrdCl::FileSystem::DeepLocate(const std::string &, XrdCl::OpenFlags::Flags, XrdCl::LocationInfo *&, uint16_t) (" __HERE__ ")");
    // signature to use in the veto list: XrdCl::XRootDStatus XrdCl::FileSystem::DeepLocate(const std::string &, XrdCl::OpenFlags::Flags, XrdCl::LocationInfo *&, uint16_t)
    // defined in /Users/mato/.julia/artifacts/d7f8626a7055397045bff10d1f18132236662705/include/xrootd/XrdCl/XrdClFileSystem.hh:285:20
    t.method("DeepLocate", [](XrdCl::FileSystem& a, const std::string & arg0, XrdCl::OpenFlags::Flags arg1, XrdCl::LocationInfo *& arg2)->XrdCl::XRootDStatus { return a.DeepLocate(arg0, arg1, arg2); }, jlcxx::arg("this"), jlcxx::arg("path"), jlcxx::arg("flags"), jlcxx::arg("response"));
    t.method("DeepLocate", [](XrdCl::FileSystem& a, const std::string & arg0, XrdCl::OpenFlags::Flags arg1, XrdCl::LocationInfo *& arg2, uint16_t arg3)->XrdCl::XRootDStatus { return a.DeepLocate(arg0, arg1, arg2, arg3); }, jlcxx::arg("this"), jlcxx::arg("path"), jlcxx::arg("flags"), jlcxx::arg("response"), jlcxx::arg("timeout"));
    t.method("DeepLocate", [](XrdCl::FileSystem* a, const std::string & arg0, XrdCl::OpenFlags::Flags arg1, XrdCl::LocationInfo *& arg2)->XrdCl::XRootDStatus { return a->DeepLocate(arg0, arg1, arg2); }, jlcxx::arg("this"), jlcxx::arg("path"), jlcxx::arg("flags"), jlcxx::arg("response"));
    t.method("DeepLocate", [](XrdCl::FileSystem* a, const std::string & arg0, XrdCl::OpenFlags::Flags arg1, XrdCl::LocationInfo *& arg2, uint16_t arg3)->XrdCl::XRootDStatus { return a->DeepLocate(arg0, arg1, arg2, arg3); }, jlcxx::arg("this"), jlcxx::arg("path"), jlcxx::arg("flags"), jlcxx::arg("response"), jlcxx::arg("timeout"));

    DEBUG_MSG("Adding wrapper for XrdCl::XRootDStatus XrdCl::FileSystem::Mv(const std::string &, const std::string &, XrdCl::ResponseHandler *, uint16_t) (" __HERE__ ")");
    // signature to use in the veto list: XrdCl::XRootDStatus XrdCl::FileSystem::Mv(const std::string &, const std::string &, XrdCl::ResponseHandler *, uint16_t)
    // defined in /Users/mato/.julia/artifacts/d7f8626a7055397045bff10d1f18132236662705/include/xrootd/XrdCl/XrdClFileSystem.hh:301:20
    t.method("Mv", [](XrdCl::FileSystem& a, const std::string & arg0, const std::string & arg1, XrdCl::ResponseHandler * arg2)->XrdCl::XRootDStatus { return a.Mv(arg0, arg1, arg2); }, jlcxx::arg("this"), jlcxx::arg("source"), jlcxx::arg("dest"), jlcxx::arg("handler"));
    t.method("Mv", [](XrdCl::FileSystem& a, const std::string & arg0, const std::string & arg1, XrdCl::ResponseHandler * arg2, uint16_t arg3)->XrdCl::XRootDStatus { return a.Mv(arg0, arg1, arg2, arg3); }, jlcxx::arg("this"), jlcxx::arg("source"), jlcxx::arg("dest"), jlcxx::arg("handler"), jlcxx::arg("timeout"));
    t.method("Mv", [](XrdCl::FileSystem* a, const std::string & arg0, const std::string & arg1, XrdCl::ResponseHandler * arg2)->XrdCl::XRootDStatus { return a->Mv(arg0, arg1, arg2); }, jlcxx::arg("this"), jlcxx::arg("source"), jlcxx::arg("dest"), jlcxx::arg("handler"));
    t.method("Mv", [](XrdCl::FileSystem* a, const std::string & arg0, const std::string & arg1, XrdCl::ResponseHandler * arg2, uint16_t arg3)->XrdCl::XRootDStatus { return a->Mv(arg0, arg1, arg2, arg3); }, jlcxx::arg("this"), jlcxx::arg("source"), jlcxx::arg("dest"), jlcxx::arg("handler"), jlcxx::arg("timeout"));

    DEBUG_MSG("Adding wrapper for XrdCl::XRootDStatus XrdCl::FileSystem::Mv(const std::string &, const std::string &, uint16_t) (" __HERE__ ")");
    // signature to use in the veto list: XrdCl::XRootDStatus XrdCl::FileSystem::Mv(const std::string &, const std::string &, uint16_t)
    // defined in /Users/mato/.julia/artifacts/d7f8626a7055397045bff10d1f18132236662705/include/xrootd/XrdCl/XrdClFileSystem.hh:316:20
    t.method("Mv", [](XrdCl::FileSystem& a, const std::string & arg0, const std::string & arg1)->XrdCl::XRootDStatus { return a.Mv(arg0, arg1); }, jlcxx::arg("this"), jlcxx::arg("source"), jlcxx::arg("dest"));
    t.method("Mv", [](XrdCl::FileSystem& a, const std::string & arg0, const std::string & arg1, uint16_t arg2)->XrdCl::XRootDStatus { return a.Mv(arg0, arg1, arg2); }, jlcxx::arg("this"), jlcxx::arg("source"), jlcxx::arg("dest"), jlcxx::arg("timeout"));
    t.method("Mv", [](XrdCl::FileSystem* a, const std::string & arg0, const std::string & arg1)->XrdCl::XRootDStatus { return a->Mv(arg0, arg1); }, jlcxx::arg("this"), jlcxx::arg("source"), jlcxx::arg("dest"));
    t.method("Mv", [](XrdCl::FileSystem* a, const std::string & arg0, const std::string & arg1, uint16_t arg2)->XrdCl::XRootDStatus { return a->Mv(arg0, arg1, arg2); }, jlcxx::arg("this"), jlcxx::arg("source"), jlcxx::arg("dest"), jlcxx::arg("timeout"));

    DEBUG_MSG("Adding wrapper for XrdCl::XRootDStatus XrdCl::FileSystem::Query(XrdCl::QueryCode::Code, const XrdCl::Buffer &, XrdCl::ResponseHandler *, uint16_t) (" __HERE__ ")");
    // signature to use in the veto list: XrdCl::XRootDStatus XrdCl::FileSystem::Query(XrdCl::QueryCode::Code, const XrdCl::Buffer &, XrdCl::ResponseHandler *, uint16_t)
    // defined in /Users/mato/.julia/artifacts/d7f8626a7055397045bff10d1f18132236662705/include/xrootd/XrdCl/XrdClFileSystem.hh:333:20
    t.method("Query", [](XrdCl::FileSystem& a, XrdCl::QueryCode::Code arg0, const XrdCl::Buffer & arg1, XrdCl::ResponseHandler * arg2)->XrdCl::XRootDStatus { return a.Query(arg0, arg1, arg2); }, jlcxx::arg("this"), jlcxx::arg("queryCode"), jlcxx::arg("arg"), jlcxx::arg("handler"));
    t.method("Query", [](XrdCl::FileSystem& a, XrdCl::QueryCode::Code arg0, const XrdCl::Buffer & arg1, XrdCl::ResponseHandler * arg2, uint16_t arg3)->XrdCl::XRootDStatus { return a.Query(arg0, arg1, arg2, arg3); }, jlcxx::arg("this"), jlcxx::arg("queryCode"), jlcxx::arg("arg"), jlcxx::arg("handler"), jlcxx::arg("timeout"));
    t.method("Query", [](XrdCl::FileSystem* a, XrdCl::QueryCode::Code arg0, const XrdCl::Buffer & arg1, XrdCl::ResponseHandler * arg2)->XrdCl::XRootDStatus { return a->Query(arg0, arg1, arg2); }, jlcxx::arg("this"), jlcxx::arg("queryCode"), jlcxx::arg("arg"), jlcxx::arg("handler"));
    t.method("Query", [](XrdCl::FileSystem* a, XrdCl::QueryCode::Code arg0, const XrdCl::Buffer & arg1, XrdCl::ResponseHandler * arg2, uint16_t arg3)->XrdCl::XRootDStatus { return a->Query(arg0, arg1, arg2, arg3); }, jlcxx::arg("this"), jlcxx::arg("queryCode"), jlcxx::arg("arg"), jlcxx::arg("handler"), jlcxx::arg("timeout"));

    DEBUG_MSG("Adding wrapper for XrdCl::XRootDStatus XrdCl::FileSystem::Query(XrdCl::QueryCode::Code, const XrdCl::Buffer &, XrdCl::Buffer *&, uint16_t) (" __HERE__ ")");
    // signature to use in the veto list: XrdCl::XRootDStatus XrdCl::FileSystem::Query(XrdCl::QueryCode::Code, const XrdCl::Buffer &, XrdCl::Buffer *&, uint16_t)
    // defined in /Users/mato/.julia/artifacts/d7f8626a7055397045bff10d1f18132236662705/include/xrootd/XrdCl/XrdClFileSystem.hh:349:20
    t.method("Query", [](XrdCl::FileSystem& a, XrdCl::QueryCode::Code arg0, const XrdCl::Buffer & arg1, XrdCl::Buffer *& arg2)->XrdCl::XRootDStatus { return a.Query(arg0, arg1, arg2); }, jlcxx::arg("this"), jlcxx::arg("queryCode"), jlcxx::arg("arg"), jlcxx::arg("response"));
    t.method("Query", [](XrdCl::FileSystem& a, XrdCl::QueryCode::Code arg0, const XrdCl::Buffer & arg1, XrdCl::Buffer *& arg2, uint16_t arg3)->XrdCl::XRootDStatus { return a.Query(arg0, arg1, arg2, arg3); }, jlcxx::arg("this"), jlcxx::arg("queryCode"), jlcxx::arg("arg"), jlcxx::arg("response"), jlcxx::arg("timeout"));
    t.method("Query", [](XrdCl::FileSystem* a, XrdCl::QueryCode::Code arg0, const XrdCl::Buffer & arg1, XrdCl::Buffer *& arg2)->XrdCl::XRootDStatus { return a->Query(arg0, arg1, arg2); }, jlcxx::arg("this"), jlcxx::arg("queryCode"), jlcxx::arg("arg"), jlcxx::arg("response"));
    t.method("Query", [](XrdCl::FileSystem* a, XrdCl::QueryCode::Code arg0, const XrdCl::Buffer & arg1, XrdCl::Buffer *& arg2, uint16_t arg3)->XrdCl::XRootDStatus { return a->Query(arg0, arg1, arg2, arg3); }, jlcxx::arg("this"), jlcxx::arg("queryCode"), jlcxx::arg("arg"), jlcxx::arg("response"), jlcxx::arg("timeout"));

    DEBUG_MSG("Adding wrapper for XrdCl::XRootDStatus XrdCl::FileSystem::Truncate(const std::string &, uint64_t, XrdCl::ResponseHandler *, uint16_t) (" __HERE__ ")");
    // signature to use in the veto list: XrdCl::XRootDStatus XrdCl::FileSystem::Truncate(const std::string &, uint64_t, XrdCl::ResponseHandler *, uint16_t)
    // defined in /Users/mato/.julia/artifacts/d7f8626a7055397045bff10d1f18132236662705/include/xrootd/XrdCl/XrdClFileSystem.hh:365:20
    t.method("Truncate", [](XrdCl::FileSystem& a, const std::string & arg0, uint64_t arg1, XrdCl::ResponseHandler * arg2)->XrdCl::XRootDStatus { return a.Truncate(arg0, arg1, arg2); }, jlcxx::arg("this"), jlcxx::arg("path"), jlcxx::arg("size"), jlcxx::arg("handler"));
    t.method("Truncate", [](XrdCl::FileSystem& a, const std::string & arg0, uint64_t arg1, XrdCl::ResponseHandler * arg2, uint16_t arg3)->XrdCl::XRootDStatus { return a.Truncate(arg0, arg1, arg2, arg3); }, jlcxx::arg("this"), jlcxx::arg("path"), jlcxx::arg("size"), jlcxx::arg("handler"), jlcxx::arg("timeout"));
    t.method("Truncate", [](XrdCl::FileSystem* a, const std::string & arg0, uint64_t arg1, XrdCl::ResponseHandler * arg2)->XrdCl::XRootDStatus { return a->Truncate(arg0, arg1, arg2); }, jlcxx::arg("this"), jlcxx::arg("path"), jlcxx::arg("size"), jlcxx::arg("handler"));
    t.method("Truncate", [](XrdCl::FileSystem* a, const std::string & arg0, uint64_t arg1, XrdCl::ResponseHandler * arg2, uint16_t arg3)->XrdCl::XRootDStatus { return a->Truncate(arg0, arg1, arg2, arg3); }, jlcxx::arg("this"), jlcxx::arg("path"), jlcxx::arg("size"), jlcxx::arg("handler"), jlcxx::arg("timeout"));

    DEBUG_MSG("Adding wrapper for XrdCl::XRootDStatus XrdCl::FileSystem::Truncate(const std::string &, uint64_t, uint16_t) (" __HERE__ ")");
    // signature to use in the veto list: XrdCl::XRootDStatus XrdCl::FileSystem::Truncate(const std::string &, uint64_t, uint16_t)
    // defined in /Users/mato/.julia/artifacts/d7f8626a7055397045bff10d1f18132236662705/include/xrootd/XrdCl/XrdClFileSystem.hh:380:20
    t.method("Truncate", [](XrdCl::FileSystem& a, const std::string & arg0, uint64_t arg1)->XrdCl::XRootDStatus { return a.Truncate(arg0, arg1); }, jlcxx::arg("this"), jlcxx::arg("path"), jlcxx::arg("size"));
    t.method("Truncate", [](XrdCl::FileSystem& a, const std::string & arg0, uint64_t arg1, uint16_t arg2)->XrdCl::XRootDStatus { return a.Truncate(arg0, arg1, arg2); }, jlcxx::arg("this"), jlcxx::arg("path"), jlcxx::arg("size"), jlcxx::arg("timeout"));
    t.method("Truncate", [](XrdCl::FileSystem* a, const std::string & arg0, uint64_t arg1)->XrdCl::XRootDStatus { return a->Truncate(arg0, arg1); }, jlcxx::arg("this"), jlcxx::arg("path"), jlcxx::arg("size"));
    t.method("Truncate", [](XrdCl::FileSystem* a, const std::string & arg0, uint64_t arg1, uint16_t arg2)->XrdCl::XRootDStatus { return a->Truncate(arg0, arg1, arg2); }, jlcxx::arg("this"), jlcxx::arg("path"), jlcxx::arg("size"), jlcxx::arg("timeout"));

    DEBUG_MSG("Adding wrapper for XrdCl::XRootDStatus XrdCl::FileSystem::Rm(const std::string &, XrdCl::ResponseHandler *, uint16_t) (" __HERE__ ")");
    // signature to use in the veto list: XrdCl::XRootDStatus XrdCl::FileSystem::Rm(const std::string &, XrdCl::ResponseHandler *, uint16_t)
    // defined in /Users/mato/.julia/artifacts/d7f8626a7055397045bff10d1f18132236662705/include/xrootd/XrdCl/XrdClFileSystem.hh:394:20
    t.method("Rm", [](XrdCl::FileSystem& a, const std::string & arg0, XrdCl::ResponseHandler * arg1)->XrdCl::XRootDStatus { return a.Rm(arg0, arg1); }, jlcxx::arg("this"), jlcxx::arg("path"), jlcxx::arg("handler"));
    t.method("Rm", [](XrdCl::FileSystem& a, const std::string & arg0, XrdCl::ResponseHandler * arg1, uint16_t arg2)->XrdCl::XRootDStatus { return a.Rm(arg0, arg1, arg2); }, jlcxx::arg("this"), jlcxx::arg("path"), jlcxx::arg("handler"), jlcxx::arg("timeout"));
    t.method("Rm", [](XrdCl::FileSystem* a, const std::string & arg0, XrdCl::ResponseHandler * arg1)->XrdCl::XRootDStatus { return a->Rm(arg0, arg1); }, jlcxx::arg("this"), jlcxx::arg("path"), jlcxx::arg("handler"));
    t.method("Rm", [](XrdCl::FileSystem* a, const std::string & arg0, XrdCl::ResponseHandler * arg1, uint16_t arg2)->XrdCl::XRootDStatus { return a->Rm(arg0, arg1, arg2); }, jlcxx::arg("this"), jlcxx::arg("path"), jlcxx::arg("handler"), jlcxx::arg("timeout"));

    DEBUG_MSG("Adding wrapper for XrdCl::XRootDStatus XrdCl::FileSystem::Rm(const std::string &, uint16_t) (" __HERE__ ")");
    // signature to use in the veto list: XrdCl::XRootDStatus XrdCl::FileSystem::Rm(const std::string &, uint16_t)
    // defined in /Users/mato/.julia/artifacts/d7f8626a7055397045bff10d1f18132236662705/include/xrootd/XrdCl/XrdClFileSystem.hh:407:20
    t.method("Rm", [](XrdCl::FileSystem& a, const std::string & arg0)->XrdCl::XRootDStatus { return a.Rm(arg0); }, jlcxx::arg("this"), jlcxx::arg("path"));
    t.method("Rm", [](XrdCl::FileSystem& a, const std::string & arg0, uint16_t arg1)->XrdCl::XRootDStatus { return a.Rm(arg0, arg1); }, jlcxx::arg("this"), jlcxx::arg("path"), jlcxx::arg("timeout"));
    t.method("Rm", [](XrdCl::FileSystem* a, const std::string & arg0)->XrdCl::XRootDStatus { return a->Rm(arg0); }, jlcxx::arg("this"), jlcxx::arg("path"));
    t.method("Rm", [](XrdCl::FileSystem* a, const std::string & arg0, uint16_t arg1)->XrdCl::XRootDStatus { return a->Rm(arg0, arg1); }, jlcxx::arg("this"), jlcxx::arg("path"), jlcxx::arg("timeout"));

    DEBUG_MSG("Adding wrapper for XrdCl::XRootDStatus XrdCl::FileSystem::MkDir(const std::string &, XrdCl::MkDirFlags::Flags, XrdCl::Access::Mode, XrdCl::ResponseHandler *, uint16_t) (" __HERE__ ")");
    // signature to use in the veto list: XrdCl::XRootDStatus XrdCl::FileSystem::MkDir(const std::string &, XrdCl::MkDirFlags::Flags, XrdCl::Access::Mode, XrdCl::ResponseHandler *, uint16_t)
    // defined in /Users/mato/.julia/artifacts/d7f8626a7055397045bff10d1f18132236662705/include/xrootd/XrdCl/XrdClFileSystem.hh:422:20
    t.method("MkDir", [](XrdCl::FileSystem& a, const std::string & arg0, XrdCl::MkDirFlags::Flags arg1, XrdCl::Access::Mode arg2, XrdCl::ResponseHandler * arg3)->XrdCl::XRootDStatus { return a.MkDir(arg0, arg1, arg2, arg3); }, jlcxx::arg("this"), jlcxx::arg("path"), jlcxx::arg("flags"), jlcxx::arg("mode"), jlcxx::arg("handler"));
    t.method("MkDir", [](XrdCl::FileSystem& a, const std::string & arg0, XrdCl::MkDirFlags::Flags arg1, XrdCl::Access::Mode arg2, XrdCl::ResponseHandler * arg3, uint16_t arg4)->XrdCl::XRootDStatus { return a.MkDir(arg0, arg1, arg2, arg3, arg4); }, jlcxx::arg("this"), jlcxx::arg("path"), jlcxx::arg("flags"), jlcxx::arg("mode"), jlcxx::arg("handler"), jlcxx::arg("timeout"));
    t.method("MkDir", [](XrdCl::FileSystem* a, const std::string & arg0, XrdCl::MkDirFlags::Flags arg1, XrdCl::Access::Mode arg2, XrdCl::ResponseHandler * arg3)->XrdCl::XRootDStatus { return a->MkDir(arg0, arg1, arg2, arg3); }, jlcxx::arg("this"), jlcxx::arg("path"), jlcxx::arg("flags"), jlcxx::arg("mode"), jlcxx::arg("handler"));
    t.method("MkDir", [](XrdCl::FileSystem* a, const std::string & arg0, XrdCl::MkDirFlags::Flags arg1, XrdCl::Access::Mode arg2, XrdCl::ResponseHandler * arg3, uint16_t arg4)->XrdCl::XRootDStatus { return a->MkDir(arg0, arg1, arg2, arg3, arg4); }, jlcxx::arg("this"), jlcxx::arg("path"), jlcxx::arg("flags"), jlcxx::arg("mode"), jlcxx::arg("handler"), jlcxx::arg("timeout"));

    DEBUG_MSG("Adding wrapper for XrdCl::XRootDStatus XrdCl::FileSystem::MkDir(const std::string &, XrdCl::MkDirFlags::Flags, XrdCl::Access::Mode, uint16_t) (" __HERE__ ")");
    // signature to use in the veto list: XrdCl::XRootDStatus XrdCl::FileSystem::MkDir(const std::string &, XrdCl::MkDirFlags::Flags, XrdCl::Access::Mode, uint16_t)
    // defined in /Users/mato/.julia/artifacts/d7f8626a7055397045bff10d1f18132236662705/include/xrootd/XrdCl/XrdClFileSystem.hh:439:20
    t.method("MkDir", [](XrdCl::FileSystem& a, const std::string & arg0, XrdCl::MkDirFlags::Flags arg1, XrdCl::Access::Mode arg2)->XrdCl::XRootDStatus { return a.MkDir(arg0, arg1, arg2); }, jlcxx::arg("this"), jlcxx::arg("path"), jlcxx::arg("flags"), jlcxx::arg("mode"));
    t.method("MkDir", [](XrdCl::FileSystem& a, const std::string & arg0, XrdCl::MkDirFlags::Flags arg1, XrdCl::Access::Mode arg2, uint16_t arg3)->XrdCl::XRootDStatus { return a.MkDir(arg0, arg1, arg2, arg3); }, jlcxx::arg("this"), jlcxx::arg("path"), jlcxx::arg("flags"), jlcxx::arg("mode"), jlcxx::arg("timeout"));
    t.method("MkDir", [](XrdCl::FileSystem* a, const std::string & arg0, XrdCl::MkDirFlags::Flags arg1, XrdCl::Access::Mode arg2)->XrdCl::XRootDStatus { return a->MkDir(arg0, arg1, arg2); }, jlcxx::arg("this"), jlcxx::arg("path"), jlcxx::arg("flags"), jlcxx::arg("mode"));
    t.method("MkDir", [](XrdCl::FileSystem* a, const std::string & arg0, XrdCl::MkDirFlags::Flags arg1, XrdCl::Access::Mode arg2, uint16_t arg3)->XrdCl::XRootDStatus { return a->MkDir(arg0, arg1, arg2, arg3); }, jlcxx::arg("this"), jlcxx::arg("path"), jlcxx::arg("flags"), jlcxx::arg("mode"), jlcxx::arg("timeout"));

    DEBUG_MSG("Adding wrapper for XrdCl::XRootDStatus XrdCl::FileSystem::RmDir(const std::string &, XrdCl::ResponseHandler *, uint16_t) (" __HERE__ ")");
    // signature to use in the veto list: XrdCl::XRootDStatus XrdCl::FileSystem::RmDir(const std::string &, XrdCl::ResponseHandler *, uint16_t)
    // defined in /Users/mato/.julia/artifacts/d7f8626a7055397045bff10d1f18132236662705/include/xrootd/XrdCl/XrdClFileSystem.hh:454:20
    t.method("RmDir", [](XrdCl::FileSystem& a, const std::string & arg0, XrdCl::ResponseHandler * arg1)->XrdCl::XRootDStatus { return a.RmDir(arg0, arg1); }, jlcxx::arg("this"), jlcxx::arg("path"), jlcxx::arg("handler"));
    t.method("RmDir", [](XrdCl::FileSystem& a, const std::string & arg0, XrdCl::ResponseHandler * arg1, uint16_t arg2)->XrdCl::XRootDStatus { return a.RmDir(arg0, arg1, arg2); }, jlcxx::arg("this"), jlcxx::arg("path"), jlcxx::arg("handler"), jlcxx::arg("timeout"));
    t.method("RmDir", [](XrdCl::FileSystem* a, const std::string & arg0, XrdCl::ResponseHandler * arg1)->XrdCl::XRootDStatus { return a->RmDir(arg0, arg1); }, jlcxx::arg("this"), jlcxx::arg("path"), jlcxx::arg("handler"));
    t.method("RmDir", [](XrdCl::FileSystem* a, const std::string & arg0, XrdCl::ResponseHandler * arg1, uint16_t arg2)->XrdCl::XRootDStatus { return a->RmDir(arg0, arg1, arg2); }, jlcxx::arg("this"), jlcxx::arg("path"), jlcxx::arg("handler"), jlcxx::arg("timeout"));

    DEBUG_MSG("Adding wrapper for XrdCl::XRootDStatus XrdCl::FileSystem::RmDir(const std::string &, uint16_t) (" __HERE__ ")");
    // signature to use in the veto list: XrdCl::XRootDStatus XrdCl::FileSystem::RmDir(const std::string &, uint16_t)
    // defined in /Users/mato/.julia/artifacts/d7f8626a7055397045bff10d1f18132236662705/include/xrootd/XrdCl/XrdClFileSystem.hh:467:20
    t.method("RmDir", [](XrdCl::FileSystem& a, const std::string & arg0)->XrdCl::XRootDStatus { return a.RmDir(arg0); }, jlcxx::arg("this"), jlcxx::arg("path"));
    t.method("RmDir", [](XrdCl::FileSystem& a, const std::string & arg0, uint16_t arg1)->XrdCl::XRootDStatus { return a.RmDir(arg0, arg1); }, jlcxx::arg("this"), jlcxx::arg("path"), jlcxx::arg("timeout"));
    t.method("RmDir", [](XrdCl::FileSystem* a, const std::string & arg0)->XrdCl::XRootDStatus { return a->RmDir(arg0); }, jlcxx::arg("this"), jlcxx::arg("path"));
    t.method("RmDir", [](XrdCl::FileSystem* a, const std::string & arg0, uint16_t arg1)->XrdCl::XRootDStatus { return a->RmDir(arg0, arg1); }, jlcxx::arg("this"), jlcxx::arg("path"), jlcxx::arg("timeout"));

    DEBUG_MSG("Adding wrapper for XrdCl::XRootDStatus XrdCl::FileSystem::ChMod(const std::string &, XrdCl::Access::Mode, XrdCl::ResponseHandler *, uint16_t) (" __HERE__ ")");
    // signature to use in the veto list: XrdCl::XRootDStatus XrdCl::FileSystem::ChMod(const std::string &, XrdCl::Access::Mode, XrdCl::ResponseHandler *, uint16_t)
    // defined in /Users/mato/.julia/artifacts/d7f8626a7055397045bff10d1f18132236662705/include/xrootd/XrdCl/XrdClFileSystem.hh:481:20
    t.method("ChMod", [](XrdCl::FileSystem& a, const std::string & arg0, XrdCl::Access::Mode arg1, XrdCl::ResponseHandler * arg2)->XrdCl::XRootDStatus { return a.ChMod(arg0, arg1, arg2); }, jlcxx::arg("this"), jlcxx::arg("path"), jlcxx::arg("mode"), jlcxx::arg("handler"));
    t.method("ChMod", [](XrdCl::FileSystem& a, const std::string & arg0, XrdCl::Access::Mode arg1, XrdCl::ResponseHandler * arg2, uint16_t arg3)->XrdCl::XRootDStatus { return a.ChMod(arg0, arg1, arg2, arg3); }, jlcxx::arg("this"), jlcxx::arg("path"), jlcxx::arg("mode"), jlcxx::arg("handler"), jlcxx::arg("timeout"));
    t.method("ChMod", [](XrdCl::FileSystem* a, const std::string & arg0, XrdCl::Access::Mode arg1, XrdCl::ResponseHandler * arg2)->XrdCl::XRootDStatus { return a->ChMod(arg0, arg1, arg2); }, jlcxx::arg("this"), jlcxx::arg("path"), jlcxx::arg("mode"), jlcxx::arg("handler"));
    t.method("ChMod", [](XrdCl::FileSystem* a, const std::string & arg0, XrdCl::Access::Mode arg1, XrdCl::ResponseHandler * arg2, uint16_t arg3)->XrdCl::XRootDStatus { return a->ChMod(arg0, arg1, arg2, arg3); }, jlcxx::arg("this"), jlcxx::arg("path"), jlcxx::arg("mode"), jlcxx::arg("handler"), jlcxx::arg("timeout"));

    DEBUG_MSG("Adding wrapper for XrdCl::XRootDStatus XrdCl::FileSystem::ChMod(const std::string &, XrdCl::Access::Mode, uint16_t) (" __HERE__ ")");
    // signature to use in the veto list: XrdCl::XRootDStatus XrdCl::FileSystem::ChMod(const std::string &, XrdCl::Access::Mode, uint16_t)
    // defined in /Users/mato/.julia/artifacts/d7f8626a7055397045bff10d1f18132236662705/include/xrootd/XrdCl/XrdClFileSystem.hh:496:20
    t.method("ChMod", [](XrdCl::FileSystem& a, const std::string & arg0, XrdCl::Access::Mode arg1)->XrdCl::XRootDStatus { return a.ChMod(arg0, arg1); }, jlcxx::arg("this"), jlcxx::arg("path"), jlcxx::arg("mode"));
    t.method("ChMod", [](XrdCl::FileSystem& a, const std::string & arg0, XrdCl::Access::Mode arg1, uint16_t arg2)->XrdCl::XRootDStatus { return a.ChMod(arg0, arg1, arg2); }, jlcxx::arg("this"), jlcxx::arg("path"), jlcxx::arg("mode"), jlcxx::arg("timeout"));
    t.method("ChMod", [](XrdCl::FileSystem* a, const std::string & arg0, XrdCl::Access::Mode arg1)->XrdCl::XRootDStatus { return a->ChMod(arg0, arg1); }, jlcxx::arg("this"), jlcxx::arg("path"), jlcxx::arg("mode"));
    t.method("ChMod", [](XrdCl::FileSystem* a, const std::string & arg0, XrdCl::Access::Mode arg1, uint16_t arg2)->XrdCl::XRootDStatus { return a->ChMod(arg0, arg1, arg2); }, jlcxx::arg("this"), jlcxx::arg("path"), jlcxx::arg("mode"), jlcxx::arg("timeout"));

    DEBUG_MSG("Adding wrapper for XrdCl::XRootDStatus XrdCl::FileSystem::Ping(XrdCl::ResponseHandler *, uint16_t) (" __HERE__ ")");
    // signature to use in the veto list: XrdCl::XRootDStatus XrdCl::FileSystem::Ping(XrdCl::ResponseHandler *, uint16_t)
    // defined in /Users/mato/.julia/artifacts/d7f8626a7055397045bff10d1f18132236662705/include/xrootd/XrdCl/XrdClFileSystem.hh:509:20
    t.method("Ping", [](XrdCl::FileSystem& a, XrdCl::ResponseHandler * arg0)->XrdCl::XRootDStatus { return a.Ping(arg0); }, jlcxx::arg("this"), jlcxx::arg("handler"));
    t.method("Ping", [](XrdCl::FileSystem& a, XrdCl::ResponseHandler * arg0, uint16_t arg1)->XrdCl::XRootDStatus { return a.Ping(arg0, arg1); }, jlcxx::arg("this"), jlcxx::arg("handler"), jlcxx::arg("timeout"));
    t.method("Ping", [](XrdCl::FileSystem* a, XrdCl::ResponseHandler * arg0)->XrdCl::XRootDStatus { return a->Ping(arg0); }, jlcxx::arg("this"), jlcxx::arg("handler"));
    t.method("Ping", [](XrdCl::FileSystem* a, XrdCl::ResponseHandler * arg0, uint16_t arg1)->XrdCl::XRootDStatus { return a->Ping(arg0, arg1); }, jlcxx::arg("this"), jlcxx::arg("handler"), jlcxx::arg("timeout"));

    DEBUG_MSG("Adding wrapper for XrdCl::XRootDStatus XrdCl::FileSystem::Ping(uint16_t) (" __HERE__ ")");
    // signature to use in the veto list: XrdCl::XRootDStatus XrdCl::FileSystem::Ping(uint16_t)
    // defined in /Users/mato/.julia/artifacts/d7f8626a7055397045bff10d1f18132236662705/include/xrootd/XrdCl/XrdClFileSystem.hh:520:20
    t.method("Ping", [](XrdCl::FileSystem& a)->XrdCl::XRootDStatus { return a.Ping(); }, jlcxx::arg("this"));
    t.method("Ping", [](XrdCl::FileSystem& a, uint16_t arg0)->XrdCl::XRootDStatus { return a.Ping(arg0); }, jlcxx::arg("this"), jlcxx::arg("timeout"));
    t.method("Ping", [](XrdCl::FileSystem* a)->XrdCl::XRootDStatus { return a->Ping(); }, jlcxx::arg("this"));
    t.method("Ping", [](XrdCl::FileSystem* a, uint16_t arg0)->XrdCl::XRootDStatus { return a->Ping(arg0); }, jlcxx::arg("this"), jlcxx::arg("timeout"));

    DEBUG_MSG("Adding wrapper for XrdCl::XRootDStatus XrdCl::FileSystem::Stat(const std::string &, XrdCl::ResponseHandler *, uint16_t) (" __HERE__ ")");
    // signature to use in the veto list: XrdCl::XRootDStatus XrdCl::FileSystem::Stat(const std::string &, XrdCl::ResponseHandler *, uint16_t)
    // defined in /Users/mato/.julia/artifacts/d7f8626a7055397045bff10d1f18132236662705/include/xrootd/XrdCl/XrdClFileSystem.hh:533:20
    t.method("Stat", [](XrdCl::FileSystem& a, const std::string & arg0, XrdCl::ResponseHandler * arg1)->XrdCl::XRootDStatus { return a.Stat(arg0, arg1); }, jlcxx::arg("this"), jlcxx::arg("path"), jlcxx::arg("handler"));
    t.method("Stat", [](XrdCl::FileSystem& a, const std::string & arg0, XrdCl::ResponseHandler * arg1, uint16_t arg2)->XrdCl::XRootDStatus { return a.Stat(arg0, arg1, arg2); }, jlcxx::arg("this"), jlcxx::arg("path"), jlcxx::arg("handler"), jlcxx::arg("timeout"));
    t.method("Stat", [](XrdCl::FileSystem* a, const std::string & arg0, XrdCl::ResponseHandler * arg1)->XrdCl::XRootDStatus { return a->Stat(arg0, arg1); }, jlcxx::arg("this"), jlcxx::arg("path"), jlcxx::arg("handler"));
    t.method("Stat", [](XrdCl::FileSystem* a, const std::string & arg0, XrdCl::ResponseHandler * arg1, uint16_t arg2)->XrdCl::XRootDStatus { return a->Stat(arg0, arg1, arg2); }, jlcxx::arg("this"), jlcxx::arg("path"), jlcxx::arg("handler"), jlcxx::arg("timeout"));

    DEBUG_MSG("Adding wrapper for XrdCl::XRootDStatus XrdCl::FileSystem::Stat(const std::string &, XrdCl::StatInfo *&, uint16_t) (" __HERE__ ")");
    // signature to use in the veto list: XrdCl::XRootDStatus XrdCl::FileSystem::Stat(const std::string &, XrdCl::StatInfo *&, uint16_t)
    // defined in /Users/mato/.julia/artifacts/d7f8626a7055397045bff10d1f18132236662705/include/xrootd/XrdCl/XrdClFileSystem.hh:548:20
    t.method("Stat", [](XrdCl::FileSystem& a, const std::string & arg0, XrdCl::StatInfo *& arg1)->XrdCl::XRootDStatus { return a.Stat(arg0, arg1); }, jlcxx::arg("this"), jlcxx::arg("path"), jlcxx::arg("response"));
    t.method("Stat", [](XrdCl::FileSystem& a, const std::string & arg0, XrdCl::StatInfo *& arg1, uint16_t arg2)->XrdCl::XRootDStatus { return a.Stat(arg0, arg1, arg2); }, jlcxx::arg("this"), jlcxx::arg("path"), jlcxx::arg("response"), jlcxx::arg("timeout"));
    t.method("Stat", [](XrdCl::FileSystem* a, const std::string & arg0, XrdCl::StatInfo *& arg1)->XrdCl::XRootDStatus { return a->Stat(arg0, arg1); }, jlcxx::arg("this"), jlcxx::arg("path"), jlcxx::arg("response"));
    t.method("Stat", [](XrdCl::FileSystem* a, const std::string & arg0, XrdCl::StatInfo *& arg1, uint16_t arg2)->XrdCl::XRootDStatus { return a->Stat(arg0, arg1, arg2); }, jlcxx::arg("this"), jlcxx::arg("path"), jlcxx::arg("response"), jlcxx::arg("timeout"));

    DEBUG_MSG("Adding wrapper for XrdCl::XRootDStatus XrdCl::FileSystem::StatVFS(const std::string &, XrdCl::ResponseHandler *, uint16_t) (" __HERE__ ")");
    // signature to use in the veto list: XrdCl::XRootDStatus XrdCl::FileSystem::StatVFS(const std::string &, XrdCl::ResponseHandler *, uint16_t)
    // defined in /Users/mato/.julia/artifacts/d7f8626a7055397045bff10d1f18132236662705/include/xrootd/XrdCl/XrdClFileSystem.hh:564:20
    t.method("StatVFS", [](XrdCl::FileSystem& a, const std::string & arg0, XrdCl::ResponseHandler * arg1)->XrdCl::XRootDStatus { return a.StatVFS(arg0, arg1); }, jlcxx::arg("this"), jlcxx::arg("path"), jlcxx::arg("handler"));
    t.method("StatVFS", [](XrdCl::FileSystem& a, const std::string & arg0, XrdCl::ResponseHandler * arg1, uint16_t arg2)->XrdCl::XRootDStatus { return a.StatVFS(arg0, arg1, arg2); }, jlcxx::arg("this"), jlcxx::arg("path"), jlcxx::arg("handler"), jlcxx::arg("timeout"));
    t.method("StatVFS", [](XrdCl::FileSystem* a, const std::string & arg0, XrdCl::ResponseHandler * arg1)->XrdCl::XRootDStatus { return a->StatVFS(arg0, arg1); }, jlcxx::arg("this"), jlcxx::arg("path"), jlcxx::arg("handler"));
    t.method("StatVFS", [](XrdCl::FileSystem* a, const std::string & arg0, XrdCl::ResponseHandler * arg1, uint16_t arg2)->XrdCl::XRootDStatus { return a->StatVFS(arg0, arg1, arg2); }, jlcxx::arg("this"), jlcxx::arg("path"), jlcxx::arg("handler"), jlcxx::arg("timeout"));

    DEBUG_MSG("Adding wrapper for XrdCl::XRootDStatus XrdCl::FileSystem::StatVFS(const std::string &, XrdCl::StatInfoVFS *&, uint16_t) (" __HERE__ ")");
    // signature to use in the veto list: XrdCl::XRootDStatus XrdCl::FileSystem::StatVFS(const std::string &, XrdCl::StatInfoVFS *&, uint16_t)
    // defined in /Users/mato/.julia/artifacts/d7f8626a7055397045bff10d1f18132236662705/include/xrootd/XrdCl/XrdClFileSystem.hh:578:20
    t.method("StatVFS", [](XrdCl::FileSystem& a, const std::string & arg0, XrdCl::StatInfoVFS *& arg1)->XrdCl::XRootDStatus { return a.StatVFS(arg0, arg1); }, jlcxx::arg("this"), jlcxx::arg("path"), jlcxx::arg("response"));
    t.method("StatVFS", [](XrdCl::FileSystem& a, const std::string & arg0, XrdCl::StatInfoVFS *& arg1, uint16_t arg2)->XrdCl::XRootDStatus { return a.StatVFS(arg0, arg1, arg2); }, jlcxx::arg("this"), jlcxx::arg("path"), jlcxx::arg("response"), jlcxx::arg("timeout"));
    t.method("StatVFS", [](XrdCl::FileSystem* a, const std::string & arg0, XrdCl::StatInfoVFS *& arg1)->XrdCl::XRootDStatus { return a->StatVFS(arg0, arg1); }, jlcxx::arg("this"), jlcxx::arg("path"), jlcxx::arg("response"));
    t.method("StatVFS", [](XrdCl::FileSystem* a, const std::string & arg0, XrdCl::StatInfoVFS *& arg1, uint16_t arg2)->XrdCl::XRootDStatus { return a->StatVFS(arg0, arg1, arg2); }, jlcxx::arg("this"), jlcxx::arg("path"), jlcxx::arg("response"), jlcxx::arg("timeout"));

    DEBUG_MSG("Adding wrapper for XrdCl::XRootDStatus XrdCl::FileSystem::Protocol(XrdCl::ResponseHandler *, uint16_t) (" __HERE__ ")");
    // signature to use in the veto list: XrdCl::XRootDStatus XrdCl::FileSystem::Protocol(XrdCl::ResponseHandler *, uint16_t)
    // defined in /Users/mato/.julia/artifacts/d7f8626a7055397045bff10d1f18132236662705/include/xrootd/XrdCl/XrdClFileSystem.hh:593:20
    t.method("Protocol", [](XrdCl::FileSystem& a, XrdCl::ResponseHandler * arg0)->XrdCl::XRootDStatus { return a.Protocol(arg0); }, jlcxx::arg("this"), jlcxx::arg("handler"));
    t.method("Protocol", [](XrdCl::FileSystem& a, XrdCl::ResponseHandler * arg0, uint16_t arg1)->XrdCl::XRootDStatus { return a.Protocol(arg0, arg1); }, jlcxx::arg("this"), jlcxx::arg("handler"), jlcxx::arg("timeout"));
    t.method("Protocol", [](XrdCl::FileSystem* a, XrdCl::ResponseHandler * arg0)->XrdCl::XRootDStatus { return a->Protocol(arg0); }, jlcxx::arg("this"), jlcxx::arg("handler"));
    t.method("Protocol", [](XrdCl::FileSystem* a, XrdCl::ResponseHandler * arg0, uint16_t arg1)->XrdCl::XRootDStatus { return a->Protocol(arg0, arg1); }, jlcxx::arg("this"), jlcxx::arg("handler"), jlcxx::arg("timeout"));

    DEBUG_MSG("Adding wrapper for XrdCl::XRootDStatus XrdCl::FileSystem::Protocol(XrdCl::ProtocolInfo *&, uint16_t) (" __HERE__ ")");
    // signature to use in the veto list: XrdCl::XRootDStatus XrdCl::FileSystem::Protocol(XrdCl::ProtocolInfo *&, uint16_t)
    // defined in /Users/mato/.julia/artifacts/d7f8626a7055397045bff10d1f18132236662705/include/xrootd/XrdCl/XrdClFileSystem.hh:605:20
    t.method("Protocol", [](XrdCl::FileSystem& a, XrdCl::ProtocolInfo *& arg0)->XrdCl::XRootDStatus { return a.Protocol(arg0); }, jlcxx::arg("this"), jlcxx::arg("response"));
    t.method("Protocol", [](XrdCl::FileSystem& a, XrdCl::ProtocolInfo *& arg0, uint16_t arg1)->XrdCl::XRootDStatus { return a.Protocol(arg0, arg1); }, jlcxx::arg("this"), jlcxx::arg("response"), jlcxx::arg("timeout"));
    t.method("Protocol", [](XrdCl::FileSystem* a, XrdCl::ProtocolInfo *& arg0)->XrdCl::XRootDStatus { return a->Protocol(arg0); }, jlcxx::arg("this"), jlcxx::arg("response"));
    t.method("Protocol", [](XrdCl::FileSystem* a, XrdCl::ProtocolInfo *& arg0, uint16_t arg1)->XrdCl::XRootDStatus { return a->Protocol(arg0, arg1); }, jlcxx::arg("this"), jlcxx::arg("response"), jlcxx::arg("timeout"));

    DEBUG_MSG("Adding wrapper for XrdCl::XRootDStatus XrdCl::FileSystem::DirList(const std::string &, XrdCl::DirListFlags::Flags, XrdCl::ResponseHandler *, uint16_t) (" __HERE__ ")");
    // signature to use in the veto list: XrdCl::XRootDStatus XrdCl::FileSystem::DirList(const std::string &, XrdCl::DirListFlags::Flags, XrdCl::ResponseHandler *, uint16_t)
    // defined in /Users/mato/.julia/artifacts/d7f8626a7055397045bff10d1f18132236662705/include/xrootd/XrdCl/XrdClFileSystem.hh:621:20
    t.method("DirList", [](XrdCl::FileSystem& a, const std::string & arg0, XrdCl::DirListFlags::Flags arg1, XrdCl::ResponseHandler * arg2)->XrdCl::XRootDStatus { return a.DirList(arg0, arg1, arg2); }, jlcxx::arg("this"), jlcxx::arg("path"), jlcxx::arg("flags"), jlcxx::arg("handler"));
    t.method("DirList", [](XrdCl::FileSystem& a, const std::string & arg0, XrdCl::DirListFlags::Flags arg1, XrdCl::ResponseHandler * arg2, uint16_t arg3)->XrdCl::XRootDStatus { return a.DirList(arg0, arg1, arg2, arg3); }, jlcxx::arg("this"), jlcxx::arg("path"), jlcxx::arg("flags"), jlcxx::arg("handler"), jlcxx::arg("timeout"));
    t.method("DirList", [](XrdCl::FileSystem* a, const std::string & arg0, XrdCl::DirListFlags::Flags arg1, XrdCl::ResponseHandler * arg2)->XrdCl::XRootDStatus { return a->DirList(arg0, arg1, arg2); }, jlcxx::arg("this"), jlcxx::arg("path"), jlcxx::arg("flags"), jlcxx::arg("handler"));
    t.method("DirList", [](XrdCl::FileSystem* a, const std::string & arg0, XrdCl::DirListFlags::Flags arg1, XrdCl::ResponseHandler * arg2, uint16_t arg3)->XrdCl::XRootDStatus { return a->DirList(arg0, arg1, arg2, arg3); }, jlcxx::arg("this"), jlcxx::arg("path"), jlcxx::arg("flags"), jlcxx::arg("handler"), jlcxx::arg("timeout"));

    DEBUG_MSG("Adding wrapper for XrdCl::XRootDStatus XrdCl::FileSystem::DirList(const std::string &, XrdCl::DirListFlags::Flags, XrdCl::DirectoryList *&, uint16_t) (" __HERE__ ")");
    // signature to use in the veto list: XrdCl::XRootDStatus XrdCl::FileSystem::DirList(const std::string &, XrdCl::DirListFlags::Flags, XrdCl::DirectoryList *&, uint16_t)
    // defined in /Users/mato/.julia/artifacts/d7f8626a7055397045bff10d1f18132236662705/include/xrootd/XrdCl/XrdClFileSystem.hh:637:20
    t.method("DirList", [](XrdCl::FileSystem& a, const std::string & arg0, XrdCl::DirListFlags::Flags arg1, XrdCl::DirectoryList *& arg2)->XrdCl::XRootDStatus { return a.DirList(arg0, arg1, arg2); }, jlcxx::arg("this"), jlcxx::arg("path"), jlcxx::arg("flags"), jlcxx::arg("response"));
    t.method("DirList", [](XrdCl::FileSystem& a, const std::string & arg0, XrdCl::DirListFlags::Flags arg1, XrdCl::DirectoryList *& arg2, uint16_t arg3)->XrdCl::XRootDStatus { return a.DirList(arg0, arg1, arg2, arg3); }, jlcxx::arg("this"), jlcxx::arg("path"), jlcxx::arg("flags"), jlcxx::arg("response"), jlcxx::arg("timeout"));
    t.method("DirList", [](XrdCl::FileSystem* a, const std::string & arg0, XrdCl::DirListFlags::Flags arg1, XrdCl::DirectoryList *& arg2)->XrdCl::XRootDStatus { return a->DirList(arg0, arg1, arg2); }, jlcxx::arg("this"), jlcxx::arg("path"), jlcxx::arg("flags"), jlcxx::arg("response"));
    t.method("DirList", [](XrdCl::FileSystem* a, const std::string & arg0, XrdCl::DirListFlags::Flags arg1, XrdCl::DirectoryList *& arg2, uint16_t arg3)->XrdCl::XRootDStatus { return a->DirList(arg0, arg1, arg2, arg3); }, jlcxx::arg("this"), jlcxx::arg("path"), jlcxx::arg("flags"), jlcxx::arg("response"), jlcxx::arg("timeout"));

    DEBUG_MSG("Adding wrapper for XrdCl::XRootDStatus XrdCl::FileSystem::SendCache(const std::string &, XrdCl::ResponseHandler *, uint16_t) (" __HERE__ ")");
    // signature to use in the veto list: XrdCl::XRootDStatus XrdCl::FileSystem::SendCache(const std::string &, XrdCl::ResponseHandler *, uint16_t)
    // defined in /Users/mato/.julia/artifacts/d7f8626a7055397045bff10d1f18132236662705/include/xrootd/XrdCl/XrdClFileSystem.hh:654:20
    t.method("SendCache", [](XrdCl::FileSystem& a, const std::string & arg0, XrdCl::ResponseHandler * arg1)->XrdCl::XRootDStatus { return a.SendCache(arg0, arg1); }, jlcxx::arg("this"), jlcxx::arg("info"), jlcxx::arg("handler"));
    t.method("SendCache", [](XrdCl::FileSystem& a, const std::string & arg0, XrdCl::ResponseHandler * arg1, uint16_t arg2)->XrdCl::XRootDStatus { return a.SendCache(arg0, arg1, arg2); }, jlcxx::arg("this"), jlcxx::arg("info"), jlcxx::arg("handler"), jlcxx::arg("timeout"));
    t.method("SendCache", [](XrdCl::FileSystem* a, const std::string & arg0, XrdCl::ResponseHandler * arg1)->XrdCl::XRootDStatus { return a->SendCache(arg0, arg1); }, jlcxx::arg("this"), jlcxx::arg("info"), jlcxx::arg("handler"));
    t.method("SendCache", [](XrdCl::FileSystem* a, const std::string & arg0, XrdCl::ResponseHandler * arg1, uint16_t arg2)->XrdCl::XRootDStatus { return a->SendCache(arg0, arg1, arg2); }, jlcxx::arg("this"), jlcxx::arg("info"), jlcxx::arg("handler"), jlcxx::arg("timeout"));

    DEBUG_MSG("Adding wrapper for XrdCl::XRootDStatus XrdCl::FileSystem::SendCache(const std::string &, XrdCl::Buffer *&, uint16_t) (" __HERE__ ")");
    // signature to use in the veto list: XrdCl::XRootDStatus XrdCl::FileSystem::SendCache(const std::string &, XrdCl::Buffer *&, uint16_t)
    // defined in /Users/mato/.julia/artifacts/d7f8626a7055397045bff10d1f18132236662705/include/xrootd/XrdCl/XrdClFileSystem.hh:668:20
    t.method("SendCache", [](XrdCl::FileSystem& a, const std::string & arg0, XrdCl::Buffer *& arg1)->XrdCl::XRootDStatus { return a.SendCache(arg0, arg1); }, jlcxx::arg("this"), jlcxx::arg("info"), jlcxx::arg("response"));
    t.method("SendCache", [](XrdCl::FileSystem& a, const std::string & arg0, XrdCl::Buffer *& arg1, uint16_t arg2)->XrdCl::XRootDStatus { return a.SendCache(arg0, arg1, arg2); }, jlcxx::arg("this"), jlcxx::arg("info"), jlcxx::arg("response"), jlcxx::arg("timeout"));
    t.method("SendCache", [](XrdCl::FileSystem* a, const std::string & arg0, XrdCl::Buffer *& arg1)->XrdCl::XRootDStatus { return a->SendCache(arg0, arg1); }, jlcxx::arg("this"), jlcxx::arg("info"), jlcxx::arg("response"));
    t.method("SendCache", [](XrdCl::FileSystem* a, const std::string & arg0, XrdCl::Buffer *& arg1, uint16_t arg2)->XrdCl::XRootDStatus { return a->SendCache(arg0, arg1, arg2); }, jlcxx::arg("this"), jlcxx::arg("info"), jlcxx::arg("response"), jlcxx::arg("timeout"));

    DEBUG_MSG("Adding wrapper for XrdCl::XRootDStatus XrdCl::FileSystem::SendInfo(const std::string &, XrdCl::ResponseHandler *, uint16_t) (" __HERE__ ")");
    // signature to use in the veto list: XrdCl::XRootDStatus XrdCl::FileSystem::SendInfo(const std::string &, XrdCl::ResponseHandler *, uint16_t)
    // defined in /Users/mato/.julia/artifacts/d7f8626a7055397045bff10d1f18132236662705/include/xrootd/XrdCl/XrdClFileSystem.hh:684:20
    t.method("SendInfo", [](XrdCl::FileSystem& a, const std::string & arg0, XrdCl::ResponseHandler * arg1)->XrdCl::XRootDStatus { return a.SendInfo(arg0, arg1); }, jlcxx::arg("this"), jlcxx::arg("info"), jlcxx::arg("handler"));
    t.method("SendInfo", [](XrdCl::FileSystem& a, const std::string & arg0, XrdCl::ResponseHandler * arg1, uint16_t arg2)->XrdCl::XRootDStatus { return a.SendInfo(arg0, arg1, arg2); }, jlcxx::arg("this"), jlcxx::arg("info"), jlcxx::arg("handler"), jlcxx::arg("timeout"));
    t.method("SendInfo", [](XrdCl::FileSystem* a, const std::string & arg0, XrdCl::ResponseHandler * arg1)->XrdCl::XRootDStatus { return a->SendInfo(arg0, arg1); }, jlcxx::arg("this"), jlcxx::arg("info"), jlcxx::arg("handler"));
    t.method("SendInfo", [](XrdCl::FileSystem* a, const std::string & arg0, XrdCl::ResponseHandler * arg1, uint16_t arg2)->XrdCl::XRootDStatus { return a->SendInfo(arg0, arg1, arg2); }, jlcxx::arg("this"), jlcxx::arg("info"), jlcxx::arg("handler"), jlcxx::arg("timeout"));

    DEBUG_MSG("Adding wrapper for XrdCl::XRootDStatus XrdCl::FileSystem::SendInfo(const std::string &, XrdCl::Buffer *&, uint16_t) (" __HERE__ ")");
    // signature to use in the veto list: XrdCl::XRootDStatus XrdCl::FileSystem::SendInfo(const std::string &, XrdCl::Buffer *&, uint16_t)
    // defined in /Users/mato/.julia/artifacts/d7f8626a7055397045bff10d1f18132236662705/include/xrootd/XrdCl/XrdClFileSystem.hh:698:20
    t.method("SendInfo", [](XrdCl::FileSystem& a, const std::string & arg0, XrdCl::Buffer *& arg1)->XrdCl::XRootDStatus { return a.SendInfo(arg0, arg1); }, jlcxx::arg("this"), jlcxx::arg("info"), jlcxx::arg("response"));
    t.method("SendInfo", [](XrdCl::FileSystem& a, const std::string & arg0, XrdCl::Buffer *& arg1, uint16_t arg2)->XrdCl::XRootDStatus { return a.SendInfo(arg0, arg1, arg2); }, jlcxx::arg("this"), jlcxx::arg("info"), jlcxx::arg("response"), jlcxx::arg("timeout"));
    t.method("SendInfo", [](XrdCl::FileSystem* a, const std::string & arg0, XrdCl::Buffer *& arg1)->XrdCl::XRootDStatus { return a->SendInfo(arg0, arg1); }, jlcxx::arg("this"), jlcxx::arg("info"), jlcxx::arg("response"));
    t.method("SendInfo", [](XrdCl::FileSystem* a, const std::string & arg0, XrdCl::Buffer *& arg1, uint16_t arg2)->XrdCl::XRootDStatus { return a->SendInfo(arg0, arg1, arg2); }, jlcxx::arg("this"), jlcxx::arg("info"), jlcxx::arg("response"), jlcxx::arg("timeout"));

    DEBUG_MSG("Adding wrapper for XrdCl::XRootDStatus XrdCl::FileSystem::Prepare(const std::vector<std::string> &, XrdCl::PrepareFlags::Flags, uint8_t, XrdCl::ResponseHandler *, uint16_t) (" __HERE__ ")");
    // signature to use in the veto list: XrdCl::XRootDStatus XrdCl::FileSystem::Prepare(const std::vector<std::string> &, XrdCl::PrepareFlags::Flags, uint8_t, XrdCl::ResponseHandler *, uint16_t)
    // defined in /Users/mato/.julia/artifacts/d7f8626a7055397045bff10d1f18132236662705/include/xrootd/XrdCl/XrdClFileSystem.hh:716:20
    t.method("Prepare", [](XrdCl::FileSystem& a, const std::vector<std::string> & arg0, XrdCl::PrepareFlags::Flags arg1, uint8_t arg2, XrdCl::ResponseHandler * arg3)->XrdCl::XRootDStatus { return a.Prepare(arg0, arg1, arg2, arg3); }, jlcxx::arg("this"), jlcxx::arg("fileList"), jlcxx::arg("flags"), jlcxx::arg("priority"), jlcxx::arg("handler"));
    t.method("Prepare", [](XrdCl::FileSystem& a, const std::vector<std::string> & arg0, XrdCl::PrepareFlags::Flags arg1, uint8_t arg2, XrdCl::ResponseHandler * arg3, uint16_t arg4)->XrdCl::XRootDStatus { return a.Prepare(arg0, arg1, arg2, arg3, arg4); }, jlcxx::arg("this"), jlcxx::arg("fileList"), jlcxx::arg("flags"), jlcxx::arg("priority"), jlcxx::arg("handler"), jlcxx::arg("timeout"));
    t.method("Prepare", [](XrdCl::FileSystem* a, const std::vector<std::string> & arg0, XrdCl::PrepareFlags::Flags arg1, uint8_t arg2, XrdCl::ResponseHandler * arg3)->XrdCl::XRootDStatus { return a->Prepare(arg0, arg1, arg2, arg3); }, jlcxx::arg("this"), jlcxx::arg("fileList"), jlcxx::arg("flags"), jlcxx::arg("priority"), jlcxx::arg("handler"));
    t.method("Prepare", [](XrdCl::FileSystem* a, const std::vector<std::string> & arg0, XrdCl::PrepareFlags::Flags arg1, uint8_t arg2, XrdCl::ResponseHandler * arg3, uint16_t arg4)->XrdCl::XRootDStatus { return a->Prepare(arg0, arg1, arg2, arg3, arg4); }, jlcxx::arg("this"), jlcxx::arg("fileList"), jlcxx::arg("flags"), jlcxx::arg("priority"), jlcxx::arg("handler"), jlcxx::arg("timeout"));

    DEBUG_MSG("Adding wrapper for XrdCl::XRootDStatus XrdCl::FileSystem::Prepare(const std::vector<std::string> &, XrdCl::PrepareFlags::Flags, uint8_t, XrdCl::Buffer *&, uint16_t) (" __HERE__ ")");
    // signature to use in the veto list: XrdCl::XRootDStatus XrdCl::FileSystem::Prepare(const std::vector<std::string> &, XrdCl::PrepareFlags::Flags, uint8_t, XrdCl::Buffer *&, uint16_t)
    // defined in /Users/mato/.julia/artifacts/d7f8626a7055397045bff10d1f18132236662705/include/xrootd/XrdCl/XrdClFileSystem.hh:734:20
    t.method("Prepare", [](XrdCl::FileSystem& a, const std::vector<std::string> & arg0, XrdCl::PrepareFlags::Flags arg1, uint8_t arg2, XrdCl::Buffer *& arg3)->XrdCl::XRootDStatus { return a.Prepare(arg0, arg1, arg2, arg3); }, jlcxx::arg("this"), jlcxx::arg("fileList"), jlcxx::arg("flags"), jlcxx::arg("priority"), jlcxx::arg("response"));
    t.method("Prepare", [](XrdCl::FileSystem& a, const std::vector<std::string> & arg0, XrdCl::PrepareFlags::Flags arg1, uint8_t arg2, XrdCl::Buffer *& arg3, uint16_t arg4)->XrdCl::XRootDStatus { return a.Prepare(arg0, arg1, arg2, arg3, arg4); }, jlcxx::arg("this"), jlcxx::arg("fileList"), jlcxx::arg("flags"), jlcxx::arg("priority"), jlcxx::arg("response"), jlcxx::arg("timeout"));
    t.method("Prepare", [](XrdCl::FileSystem* a, const std::vector<std::string> & arg0, XrdCl::PrepareFlags::Flags arg1, uint8_t arg2, XrdCl::Buffer *& arg3)->XrdCl::XRootDStatus { return a->Prepare(arg0, arg1, arg2, arg3); }, jlcxx::arg("this"), jlcxx::arg("fileList"), jlcxx::arg("flags"), jlcxx::arg("priority"), jlcxx::arg("response"));
    t.method("Prepare", [](XrdCl::FileSystem* a, const std::vector<std::string> & arg0, XrdCl::PrepareFlags::Flags arg1, uint8_t arg2, XrdCl::Buffer *& arg3, uint16_t arg4)->XrdCl::XRootDStatus { return a->Prepare(arg0, arg1, arg2, arg3, arg4); }, jlcxx::arg("this"), jlcxx::arg("fileList"), jlcxx::arg("flags"), jlcxx::arg("priority"), jlcxx::arg("response"), jlcxx::arg("timeout"));

    DEBUG_MSG("Adding wrapper for bool XrdCl::FileSystem::SetProperty(const std::string &, const std::string &) (" __HERE__ ")");
    // signature to use in the veto list: bool XrdCl::FileSystem::SetProperty(const std::string &, const std::string &)
    // defined in /Users/mato/.julia/artifacts/d7f8626a7055397045bff10d1f18132236662705/include/xrootd/XrdCl/XrdClFileSystem.hh:871:12
    t.method("SetProperty", [](XrdCl::FileSystem& a, const std::string & arg0, const std::string & arg1)->bool { return a.SetProperty(arg0, arg1); }, jlcxx::arg("this"), jlcxx::arg("name"), jlcxx::arg("value"));
    t.method("SetProperty", [](XrdCl::FileSystem* a, const std::string & arg0, const std::string & arg1)->bool { return a->SetProperty(arg0, arg1); }, jlcxx::arg("this"), jlcxx::arg("name"), jlcxx::arg("value"));

    DEBUG_MSG("Adding wrapper for bool XrdCl::FileSystem::GetProperty(const std::string &, std::string &) (" __HERE__ ")");
    // signature to use in the veto list: bool XrdCl::FileSystem::GetProperty(const std::string &, std::string &)
    // defined in /Users/mato/.julia/artifacts/d7f8626a7055397045bff10d1f18132236662705/include/xrootd/XrdCl/XrdClFileSystem.hh:878:12
    t.method("GetProperty", [](XrdCl::FileSystem const& a, const std::string & arg0, std::string & arg1)->bool { return a.GetProperty(arg0, arg1); }, jlcxx::arg("this"), jlcxx::arg("name"), jlcxx::arg("value"));
    t.method("GetProperty", [](XrdCl::FileSystem const* a, const std::string & arg0, std::string & arg1)->bool { return a->GetProperty(arg0, arg1); }, jlcxx::arg("this"), jlcxx::arg("name"), jlcxx::arg("value"));
  }

private:
  std::unique_ptr<jlcxx::TypeWrapper<XrdCl::FileSystem>> type_;
};
std::shared_ptr<Wrapper> newJlXrdCl_FileSystem(jlcxx::Module& module){
  return std::shared_ptr<Wrapper>(new JlXrdCl_FileSystem(module));
}
