// this file was auto-generated by wrapit v1.3.1-dirty
#include "Wrapper.h"

#include "jlXRootD.h"
#include "dbg_msg.h"
#include "jlcxx/functions.hpp"
#include "jlcxx/stl.hpp"

namespace jlcxx {
  template<> struct IsMirroredType<XrdCl::OpenFlags> : std::false_type { };
  template<> struct DefaultConstructible<XrdCl::OpenFlags> : std::false_type { };
}

// Class generating the wrapper for type XrdCl::OpenFlags
// signature to use in the veto file: XrdCl::OpenFlags
struct JlXrdCl_OpenFlags: public Wrapper {

  JlXrdCl_OpenFlags(jlcxx::Module& jlModule): Wrapper(jlModule){
    DEBUG_MSG("Adding wrapper for type XrdCl::OpenFlags (" __HERE__ ")");
    // defined in /Users/mato/.julia/artifacts/d6b4bfcd1db9f33711a4c083d9d997b32d266141/include/xrootd/XrdCl/XrdClFileSystem.hh:70:10
    jlcxx::TypeWrapper<XrdCl::OpenFlags>  t = jlModule.add_type<XrdCl::OpenFlags>("XrdCl!OpenFlags");
    type_ = std::unique_ptr<jlcxx::TypeWrapper<XrdCl::OpenFlags>>(new jlcxx::TypeWrapper<XrdCl::OpenFlags>(jlModule, t));
  }

  void add_methods() const{
    auto& t = *type_;
    t.template constructor<>(/*finalize=*/true);
  }

private:
  std::unique_ptr<jlcxx::TypeWrapper<XrdCl::OpenFlags>> type_;
};
std::shared_ptr<Wrapper> newJlXrdCl_OpenFlags(jlcxx::Module& module){
  return std::shared_ptr<Wrapper>(new JlXrdCl_OpenFlags(module));
}
