// this file was auto-generated by wrapit 5168a24
#include "Wrapper.h"

#include "jlXRootD.h"
#include "dbg_msg.h"
#include "jlcxx/functions.hpp"
#include "jlcxx/stl.hpp"

namespace jlcxx {
  template<> struct IsMirroredType<XrdCl::VectorReadInfo> : std::false_type { };
  template<> struct DefaultConstructible<XrdCl::VectorReadInfo> : std::false_type { };
}

// Class generating the wrapper for type XrdCl::VectorReadInfo
// signature to use in the veto file: XrdCl::VectorReadInfo
struct JlXrdCl_VectorReadInfo: public Wrapper {

  JlXrdCl_VectorReadInfo(jlcxx::Module& jlModule): Wrapper(jlModule){
    DEBUG_MSG("Adding wrapper for type XrdCl::VectorReadInfo (" __HERE__ ")");
    // defined in /Users/mato/.julia/artifacts/8520a52585f5eadf78b58f2d486d1abb34f514f1/include/xrootd/XrdCl/XrdClXRootDResponses.hh:1060:9
    jlcxx::TypeWrapper<XrdCl::VectorReadInfo>  t = jlModule.add_type<XrdCl::VectorReadInfo>("XrdCl!VectorReadInfo");
    type_ = std::unique_ptr<jlcxx::TypeWrapper<XrdCl::VectorReadInfo>>(new jlcxx::TypeWrapper<XrdCl::VectorReadInfo>(jlModule, t));
  }

  void add_methods() const{
    auto& t = *type_;
    t.template constructor<>(/*finalize=*/jlcxx::finalize_policy::yes);

    DEBUG_MSG("Adding wrapper for uint32_t XrdCl::VectorReadInfo::GetSize() (" __HERE__ ")");
    // signature to use in the veto list: uint32_t XrdCl::VectorReadInfo::GetSize()
    // defined in /Users/mato/.julia/artifacts/8520a52585f5eadf78b58f2d486d1abb34f514f1/include/xrootd/XrdCl/XrdClXRootDResponses.hh:1071:16
    t.method("GetSize", static_cast<uint32_t (XrdCl::VectorReadInfo::*)()  const>(&XrdCl::VectorReadInfo::GetSize));

    DEBUG_MSG("Adding wrapper for void XrdCl::VectorReadInfo::SetSize(uint32_t) (" __HERE__ ")");
    // signature to use in the veto list: void XrdCl::VectorReadInfo::SetSize(uint32_t)
    // defined in /Users/mato/.julia/artifacts/8520a52585f5eadf78b58f2d486d1abb34f514f1/include/xrootd/XrdCl/XrdClXRootDResponses.hh:1079:12
    t.method("SetSize", static_cast<void (XrdCl::VectorReadInfo::*)(uint32_t) >(&XrdCl::VectorReadInfo::SetSize));

    DEBUG_MSG("Adding wrapper for XrdCl::ChunkList & XrdCl::VectorReadInfo::GetChunks() (" __HERE__ ")");
    // signature to use in the veto list: XrdCl::ChunkList & XrdCl::VectorReadInfo::GetChunks()
    // defined in /Users/mato/.julia/artifacts/8520a52585f5eadf78b58f2d486d1abb34f514f1/include/xrootd/XrdCl/XrdClXRootDResponses.hh:1087:18
    t.method("GetChunks", static_cast<XrdCl::ChunkList & (XrdCl::VectorReadInfo::*)() >(&XrdCl::VectorReadInfo::GetChunks));

    DEBUG_MSG("Adding wrapper for const XrdCl::ChunkList & XrdCl::VectorReadInfo::GetChunks() (" __HERE__ ")");
    // signature to use in the veto list: const XrdCl::ChunkList & XrdCl::VectorReadInfo::GetChunks()
    // defined in /Users/mato/.julia/artifacts/8520a52585f5eadf78b58f2d486d1abb34f514f1/include/xrootd/XrdCl/XrdClXRootDResponses.hh:1095:24
    t.method("GetChunks", static_cast<const XrdCl::ChunkList & (XrdCl::VectorReadInfo::*)()  const>(&XrdCl::VectorReadInfo::GetChunks));
  }

private:
  std::unique_ptr<jlcxx::TypeWrapper<XrdCl::VectorReadInfo>> type_;
};
std::shared_ptr<Wrapper> newJlXrdCl_VectorReadInfo(jlcxx::Module& module){
  return std::shared_ptr<Wrapper>(new JlXrdCl_VectorReadInfo(module));
}
