// this file was auto-generated by wrapit v1.6.0
#include "Wrapper.h"

#include "jlXRootD.h"
#include "dbg_msg.h"
#include "jlcxx/functions.hpp"
#include "jlcxx/stl.hpp"

namespace jlcxx {
  template<> struct IsMirroredType<XrdCl::RetryInfo> : std::false_type { };
  template<> struct DefaultConstructible<XrdCl::RetryInfo> : std::false_type { };
}

// Class generating the wrapper for type XrdCl::RetryInfo
// signature to use in the veto file: XrdCl::RetryInfo
struct JlXrdCl_RetryInfo: public Wrapper {

  JlXrdCl_RetryInfo(jlcxx::Module& jlModule): Wrapper(jlModule){
    DEBUG_MSG("Adding wrapper for type XrdCl::RetryInfo (" __HERE__ ")");
    // defined in /Users/mato/.julia/artifacts/d7f8626a7055397045bff10d1f18132236662705/include/xrootd/XrdCl/XrdClXRootDResponses.hh:1018:10
    jlcxx::TypeWrapper<XrdCl::RetryInfo>  t = jlModule.add_type<XrdCl::RetryInfo>("XrdCl!RetryInfo");
    type_ = std::unique_ptr<jlcxx::TypeWrapper<XrdCl::RetryInfo>>(new jlcxx::TypeWrapper<XrdCl::RetryInfo>(jlModule, t));
  }

  void add_methods() const{
    auto& t = *type_;


    DEBUG_MSG("Adding wrapper for bool XrdCl::RetryInfo::NeedRetry() (" __HERE__ ")");
    // signature to use in the veto list: bool XrdCl::RetryInfo::NeedRetry()
    // defined in /Users/mato/.julia/artifacts/d7f8626a7055397045bff10d1f18132236662705/include/xrootd/XrdCl/XrdClXRootDResponses.hh:1033:10
    t.method("NeedRetry", [](XrdCl::RetryInfo& a)->bool { return a.NeedRetry(); }, jlcxx::arg("this"));
    t.method("NeedRetry", [](XrdCl::RetryInfo* a)->bool { return a->NeedRetry(); }, jlcxx::arg("this"));

    DEBUG_MSG("Adding wrapper for size_t XrdCl::RetryInfo::Size() (" __HERE__ ")");
    // signature to use in the veto list: size_t XrdCl::RetryInfo::Size()
    // defined in /Users/mato/.julia/artifacts/d7f8626a7055397045bff10d1f18132236662705/include/xrootd/XrdCl/XrdClXRootDResponses.hh:1038:12
    t.method("Size", [](XrdCl::RetryInfo& a)->size_t { return a.Size(); }, jlcxx::arg("this"));
    t.method("Size", [](XrdCl::RetryInfo* a)->size_t { return a->Size(); }, jlcxx::arg("this"));
  }

private:
  std::unique_ptr<jlcxx::TypeWrapper<XrdCl::RetryInfo>> type_;
};
std::shared_ptr<Wrapper> newJlXrdCl_RetryInfo(jlcxx::Module& module){
  return std::shared_ptr<Wrapper>(new JlXrdCl_RetryInfo(module));
}
