// this file was auto-generated by wrapit 5168a24
#include "Wrapper.h"

#include "jlXRootD.h"
#include "dbg_msg.h"
#include "jlcxx/functions.hpp"
#include "jlcxx/stl.hpp"

namespace jlcxx {
  template<> struct IsMirroredType<XrdCl::PrepareFlags> : std::false_type { };
  template<> struct DefaultConstructible<XrdCl::PrepareFlags> : std::false_type { };
}

// Class generating the wrapper for type XrdCl::PrepareFlags
// signature to use in the veto file: XrdCl::PrepareFlags
struct JlXrdCl_PrepareFlags: public Wrapper {

  JlXrdCl_PrepareFlags(jlcxx::Module& jlModule): Wrapper(jlModule){
    DEBUG_MSG("Adding wrapper for type XrdCl::PrepareFlags (" __HERE__ ")");
    // defined in /Users/mato/.julia/artifacts/8520a52585f5eadf78b58f2d486d1abb34f514f1/include/xrootd/XrdCl/XrdClFileSystem.hh:173:10
    jlcxx::TypeWrapper<XrdCl::PrepareFlags>  t = jlModule.add_type<XrdCl::PrepareFlags>("XrdCl!PrepareFlags");
    type_ = std::unique_ptr<jlcxx::TypeWrapper<XrdCl::PrepareFlags>>(new jlcxx::TypeWrapper<XrdCl::PrepareFlags>(jlModule, t));
  }

  void add_methods() const{
    auto& t = *type_;
    t.template constructor<>(/*finalize=*/jlcxx::finalize_policy::yes);
  }

private:
  std::unique_ptr<jlcxx::TypeWrapper<XrdCl::PrepareFlags>> type_;
};
std::shared_ptr<Wrapper> newJlXrdCl_PrepareFlags(jlcxx::Module& module){
  return std::shared_ptr<Wrapper>(new JlXrdCl_PrepareFlags(module));
}
