// this file was auto-generated by wrapit v1.6.0
#include "Wrapper.h"

#include "jlXRootD.h"
#include "dbg_msg.h"
#include "jlcxx/functions.hpp"
#include "jlcxx/stl.hpp"

namespace jlcxx {
  template<> struct IsMirroredType<XrdCl::CopyProgressHandler> : std::false_type { };
  template<> struct DefaultConstructible<XrdCl::CopyProgressHandler> : std::false_type { };
}

// Class generating the wrapper for type XrdCl::CopyProgressHandler
// signature to use in the veto file: XrdCl::CopyProgressHandler
struct JlXrdCl_CopyProgressHandler: public Wrapper {

  JlXrdCl_CopyProgressHandler(jlcxx::Module& jlModule): Wrapper(jlModule){
    DEBUG_MSG("Adding wrapper for type XrdCl::CopyProgressHandler (" __HERE__ ")");
    // defined in /Users/mato/.julia/artifacts/d7f8626a7055397045bff10d1f18132236662705/include/xrootd/XrdCl/XrdClCopyProcess.hh:41:9
    jlcxx::TypeWrapper<XrdCl::CopyProgressHandler>  t = jlModule.add_type<XrdCl::CopyProgressHandler>("XrdCl!CopyProgressHandler");
    type_ = std::unique_ptr<jlcxx::TypeWrapper<XrdCl::CopyProgressHandler>>(new jlcxx::TypeWrapper<XrdCl::CopyProgressHandler>(jlModule, t));
  }

  void add_methods() const{
    auto& t = *type_;
    t.template constructor<>(/*finalize=*/jlcxx::finalize_policy::yes    );

    DEBUG_MSG("Adding wrapper for void XrdCl::CopyProgressHandler::BeginJob(uint16_t, uint16_t, const XrdCl::URL *, const XrdCl::URL *) (" __HERE__ ")");
    // signature to use in the veto list: void XrdCl::CopyProgressHandler::BeginJob(uint16_t, uint16_t, const XrdCl::URL *, const XrdCl::URL *)
    // defined in /Users/mato/.julia/artifacts/d7f8626a7055397045bff10d1f18132236662705/include/xrootd/XrdCl/XrdClCopyProcess.hh:54:20
    t.method("BeginJob", [](XrdCl::CopyProgressHandler& a, uint16_t arg0, uint16_t arg1, const XrdCl::URL * arg2, const XrdCl::URL * arg3)->void { a.BeginJob(arg0, arg1, arg2, arg3); }, jlcxx::arg("this"), jlcxx::arg("jobNum"), jlcxx::arg("jobTotal"), jlcxx::arg("source"), jlcxx::arg("destination"));
    t.method("BeginJob", [](XrdCl::CopyProgressHandler* a, uint16_t arg0, uint16_t arg1, const XrdCl::URL * arg2, const XrdCl::URL * arg3)->void { a->BeginJob(arg0, arg1, arg2, arg3); }, jlcxx::arg("this"), jlcxx::arg("jobNum"), jlcxx::arg("jobTotal"), jlcxx::arg("source"), jlcxx::arg("destination"));

    DEBUG_MSG("Adding wrapper for void XrdCl::CopyProgressHandler::EndJob(uint16_t, const XrdCl::PropertyList *) (" __HERE__ ")");
    // signature to use in the veto list: void XrdCl::CopyProgressHandler::EndJob(uint16_t, const XrdCl::PropertyList *)
    // defined in /Users/mato/.julia/artifacts/d7f8626a7055397045bff10d1f18132236662705/include/xrootd/XrdCl/XrdClCopyProcess.hh:68:20
    t.method("EndJob", [](XrdCl::CopyProgressHandler& a, uint16_t arg0, const XrdCl::PropertyList * arg1)->void { a.EndJob(arg0, arg1); }, jlcxx::arg("this"), jlcxx::arg("jobNum"), jlcxx::arg("result"));
    t.method("EndJob", [](XrdCl::CopyProgressHandler* a, uint16_t arg0, const XrdCl::PropertyList * arg1)->void { a->EndJob(arg0, arg1); }, jlcxx::arg("this"), jlcxx::arg("jobNum"), jlcxx::arg("result"));

    DEBUG_MSG("Adding wrapper for void XrdCl::CopyProgressHandler::JobProgress(uint16_t, uint64_t, uint64_t) (" __HERE__ ")");
    // signature to use in the veto list: void XrdCl::CopyProgressHandler::JobProgress(uint16_t, uint64_t, uint64_t)
    // defined in /Users/mato/.julia/artifacts/d7f8626a7055397045bff10d1f18132236662705/include/xrootd/XrdCl/XrdClCopyProcess.hh:82:20
    t.method("JobProgress", [](XrdCl::CopyProgressHandler& a, uint16_t arg0, uint64_t arg1, uint64_t arg2)->void { a.JobProgress(arg0, arg1, arg2); }, jlcxx::arg("this"), jlcxx::arg("jobNum"), jlcxx::arg("bytesProcessed"), jlcxx::arg("bytesTotal"));
    t.method("JobProgress", [](XrdCl::CopyProgressHandler* a, uint16_t arg0, uint64_t arg1, uint64_t arg2)->void { a->JobProgress(arg0, arg1, arg2); }, jlcxx::arg("this"), jlcxx::arg("jobNum"), jlcxx::arg("bytesProcessed"), jlcxx::arg("bytesTotal"));

    DEBUG_MSG("Adding wrapper for bool XrdCl::CopyProgressHandler::ShouldCancel(uint16_t) (" __HERE__ ")");
    // signature to use in the veto list: bool XrdCl::CopyProgressHandler::ShouldCancel(uint16_t)
    // defined in /Users/mato/.julia/artifacts/d7f8626a7055397045bff10d1f18132236662705/include/xrootd/XrdCl/XrdClCopyProcess.hh:92:20
    t.method("ShouldCancel", [](XrdCl::CopyProgressHandler& a, uint16_t arg0)->bool { return a.ShouldCancel(arg0); }, jlcxx::arg("this"), jlcxx::arg("jobNum"));
    t.method("ShouldCancel", [](XrdCl::CopyProgressHandler* a, uint16_t arg0)->bool { return a->ShouldCancel(arg0); }, jlcxx::arg("this"), jlcxx::arg("jobNum"));
  }

private:
  std::unique_ptr<jlcxx::TypeWrapper<XrdCl::CopyProgressHandler>> type_;
};
std::shared_ptr<Wrapper> newJlXrdCl_CopyProgressHandler(jlcxx::Module& module){
  return std::shared_ptr<Wrapper>(new JlXrdCl_CopyProgressHandler(module));
}
